/* Extracted from server.ts — mechanical split (pure move + import/export wiring). */

import { spawn, type ChildProcess } from "node:child_process";
import {
  appendFileSync, createReadStream, existsSync, mkdirSync,
  readFileSync, readdirSync, statSync, unlinkSync, writeFileSync,
} from "node:fs";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { basename, dirname, extname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir, networkInterfaces } from "node:os";
import { randomBytes } from "node:crypto";
import { toPosix, stripAnsi } from "./server-core.js";


/* ------------------------------ learned facts (memory) ------------------------------ */

export interface Fact {
  id: string;
  text: string;
  scope: "project" | "global";
  ticketId: string | null;
  createdTs: string;
  applied?: number;
}


/** How often each lesson was injected into an agent prompt. Written only by the
 *  factory (`memory.applied.json`); the dashboard reads it to show "used N×". */
export function readApplied(file: string): Record<string, number> {
  if (!existsSync(file)) return {};
  try {
    const raw = JSON.parse(readFileSync(file, "utf-8")) as { counts?: Record<string, number> };
    return raw.counts ?? {};
  } catch {
    return {};
  }
}


export function readFacts(file: string): Fact[] {
  if (!existsSync(file)) return [];
  try {
    return (JSON.parse(readFileSync(file, "utf-8")) as { facts?: Fact[] }).facts ?? [];
  } catch {
    return [];
  }
}


export function writeFacts(file: string, facts: Fact[]): void {
  writeFileSync(file, JSON.stringify({ facts }, null, 2), "utf-8");
}


/* ------------------------------ knowledge base (ragmcp) ------------------------------ */

// A document the dev added to the project's knowledge base. The raw file lives in
// knowledge/docs/; this is just the index entry shown in the UI.
export interface KnowledgeDoc {
  id: string;
  name: string;
  size: number;
  addedTs: string;
  chunks: number | null; // set once ragmcp has ingested it; null while pending/failed
  error?: string;
}


export function knowledgePaths(workdir: string) {
  const dir = join(workdir, "knowledge");
  return {
    dir,
    docsDir: join(dir, "docs"),
    store: join(dir, ".ragmcp"),
    yaml: join(dir, "ragmcp.yaml"),
    mcp: join(dir, "mcp.json"),
    index: join(dir, "docs.json"),
  };
}


export function readDocs(indexFile: string): KnowledgeDoc[] {
  if (!existsSync(indexFile)) return [];
  try {
    return (JSON.parse(readFileSync(indexFile, "utf-8")) as { docs?: KnowledgeDoc[] }).docs ?? [];
  } catch {
    return [];
  }
}


export function writeDocs(indexFile: string, docs: KnowledgeDoc[]): void {
  writeFileSync(indexFile, JSON.stringify({ docs }, null, 2), "utf-8");
}


// Write the per-project ragmcp config + the agent's mcp.json. Idempotent: safe to
// call on every enable. The store is scoped to this project's knowledge/.ragmcp,
// embeddings are local (fastembed, offline, no API key).
export function scaffoldKnowledge(workdir: string, ragmcp: string[]): void {
  const p = knowledgePaths(workdir);
  mkdirSync(p.docsDir, { recursive: true });
  mkdirSync(p.store, { recursive: true });
  writeFileSync(p.yaml, [
    "# Generated by the dashboard Knowledge panel. Local, offline, per-project.",
    "embedder:",
    "  provider: fastembed",
    "  model: BAAI/bge-small-en-v1.5",
    "vectorstore:",
    "  type: chroma",
    `  path: ${toPosix(p.store)}`,
    "  collection: chunks",
    "pipeline:",
    "  top_k: 8",
    "server:",
    "  transport: stdio",
    "  ingest_mode: path",
    "",
  ].join("\n"), "utf-8");
  const [cmd, ...prefix] = ragmcp;
  const mcp = {
    mcpServers: {
      ragmcp: { command: cmd, args: [...prefix, "serve", "--config", toPosix(p.yaml)] },
    },
  };
  writeFileSync(p.mcp, JSON.stringify(mcp, null, 2), "utf-8");
}


// Spawn the ragmcp CLI and resolve with its exit code + captured output. Used for
// ingest/sync; ragmcp reloads its (local) embedder per call, so this takes seconds.
export function runRagmcp(ragmcp: string[], args: string[], cwd: string): Promise<{ ok: boolean; out: string }> {
  return new Promise((resolve) => {
    const [cmd, ...prefix] = ragmcp;
    const child = spawn(cmd!, [...prefix, ...args], { cwd, shell: false, windowsHide: true });
    let out = "";
    const grab = (c: Buffer) => { out = (out + c.toString("utf-8")).slice(-20_000); };
    child.stdout.on("data", grab);
    child.stderr.on("data", grab);
    child.on("error", (err) => resolve({ ok: false, out: stripAnsi(out + "\n" + String(err)) }));
    child.on("exit", (code) => resolve({ ok: code === 0, out: stripAnsi(out).trim() }));
  });
}


// Toggle the `agent.mcp_config` line in factory.yaml. generateConfig (the Settings
// panel) also emits/preserves this exact line, so the two writers agree and a
// Settings save never clobbers an enabled knowledge base.
export const MCP_CONFIG_LINE = "  mcp_config: knowledge/mcp.json";


export function setKnowledgeEnabled(configFile: string, enabled: boolean): void {
  let text = existsSync(configFile) ? readFileSync(configFile, "utf-8") : "";
  const has = /^\s*mcp_config:/m.test(text);
  if (enabled && !has) {
    if (/^agent:\s*$/m.test(text)) {
      text = text.replace(/^agent:\s*$/m, `agent:\n${MCP_CONFIG_LINE}`);
    } else {
      text += `${text.endsWith("\n") ? "" : "\n"}agent:\n${MCP_CONFIG_LINE}\n`;
    }
    writeFileSync(configFile, text, "utf-8");
  } else if (!enabled && has) {
    writeFileSync(configFile, text.replace(/^\s*mcp_config:.*\n?/m, ""), "utf-8");
  }
}
